import { CaseNote, CaseNoteType, CaseNoteSource } from '@/types';
import {
  notion,
  DATABASE_IDS,
  queryDatabase,
  getTitle,
  getSelect,
  getDate,
  getRichText,
  getRelationIds,
  getCheckbox,
  getPeople,
  getTimestamp,
} from './client';

// Transform Notion page to CaseNote type
function transformCaseNote(page: any): CaseNote {
  const props = page.properties;

  return {
    id: page.id,
    title: getTitle(props['Note Title']),
    clientId: getRelationIds(props['Client'])[0] || '',
    date: getDate(props['Date']) || new Date().toISOString().split('T')[0],
    type: getSelect(props['Type']) as CaseNoteType,
    source: getSelect(props['Source']) as CaseNoteSource,
    fullNote: getRichText(props['Full Note']?.rich_text),
    createdBy: getPeople(props['Created By'])[0],
    autoGenerated: getCheckbox(props['Auto-Generated']),
    taskIds: getRelationIds(props['Tasks']),
    createdAt: getTimestamp(props['Created']),
    // Fireflies ownership fields
    firefliesOwnerId: getRichText(props['Fireflies Owner ID']?.rich_text) || undefined,
    firefliesOwnerEmail: getRichText(props['Fireflies Owner Email']?.rich_text) || undefined,
  };
}

// Get all case notes with optional filters
export async function getCaseNotes(options?: {
  clientId?: string;
  type?: CaseNoteType;
  source?: CaseNoteSource;
  limit?: number;
  // Fireflies owner filtering
  firefliesOwnerEmail?: string;  // Filter by specific owner email
  firefliesOwnerEmails?: string[]; // Filter by multiple owner emails (OR)
  includeNonFireflies?: boolean;   // Whether to include non-Fireflies notes (Slack, Email, Manual)
}): Promise<CaseNote[]> {
  try {
    const filters: any[] = [];

    if (options?.clientId) {
      filters.push({ property: 'Client', relation: { contains: options.clientId } });
    }
    if (options?.type) {
      filters.push({ property: 'Type', select: { equals: options.type } });
    }
    if (options?.source) {
      filters.push({ property: 'Source', select: { equals: options.source } });
    }

    // Filter by Fireflies owner email (single owner)
    if (options?.firefliesOwnerEmail) {
      filters.push({ property: 'Fireflies Owner Email', rich_text: { contains: options.firefliesOwnerEmail } });
    }

    // Filter by multiple Fireflies owner emails
    // If includeNonFireflies is true (Personal Brand team), also include notes without owner
    // If includeNonFireflies is false (other teams), ONLY show their own Fireflies notes
    if (options?.firefliesOwnerEmails && options.firefliesOwnerEmails.length > 0) {
      // OR filter for multiple owners (use contains for case-insensitive matching)
      const ownerFilters: any[] = options.firefliesOwnerEmails.map(email => ({
        property: 'Fireflies Owner Email',
        rich_text: { contains: email },
      }));

      // Only include non-Fireflies notes (empty owner) if explicitly allowed
      // This is for Personal Brand team members
      if (options.includeNonFireflies) {
        ownerFilters.push({
          property: 'Fireflies Owner Email',
          rich_text: { is_empty: true },
        });
      }

      filters.push({ or: ownerFilters });
    } else if (options?.includeNonFireflies && !options?.firefliesOwnerEmails) {
      // Admin case: no email filter, but includeNonFireflies is true
      // This means show ALL notes (no filter needed)
    }

    const response = await queryDatabase({
      database_id: DATABASE_IDS.caseNotes,
      filter: filters.length > 0 ? { and: filters } : undefined,
      sorts: [{ property: 'Date', direction: 'descending' }],
      page_size: options?.limit || 100,
    });

    return response.results.map(transformCaseNote);
  } catch (error) {
    console.error('[Case Notes] Error in getCaseNotes:', error);
    throw error;
  }
}

// Get case notes for a specific client
export async function getClientCaseNotes(clientId: string): Promise<CaseNote[]> {
  return getCaseNotes({ clientId });
}

// Get single case note by ID
export async function getCaseNote(id: string): Promise<CaseNote | null> {
  try {
    const page = await notion.pages.retrieve({ page_id: id });
    return transformCaseNote(page);
  } catch {
    return null;
  }
}

// Check if a similar case note already exists (for deduplication)
export async function findSimilarCaseNote(data: {
  clientId: string;
  title: string;
  date: string;
  source: CaseNoteSource;
}): Promise<CaseNote | null> {
  try {
    // Look for case notes with the same client, date, and source within the last 24 hours
    const response = await queryDatabase({
      database_id: DATABASE_IDS.caseNotes,
      filter: {
        and: [
          { property: 'Client', relation: { contains: data.clientId } },
          { property: 'Date', date: { equals: data.date } },
          { property: 'Source', select: { equals: data.source } },
          { property: 'Auto-Generated', checkbox: { equals: true } },
        ],
      },
      page_size: 10,
    });

    if (response.results.length === 0) return null;

    // Check for similar titles (fuzzy match)
    const normalizedNewTitle = data.title.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();

    for (const result of response.results) {
      const existingNote = transformCaseNote(result);
      const normalizedExisting = existingNote.title.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();

      // Check for exact match or high similarity
      if (normalizedExisting === normalizedNewTitle) {
        return existingNote;
      }

      // Check if one title contains the other (partial match)
      if (normalizedExisting.includes(normalizedNewTitle) || normalizedNewTitle.includes(normalizedExisting)) {
        return existingNote;
      }

      // Check word overlap (>70% similarity)
      const existingWords = new Set(normalizedExisting.split(/\s+/));
      const newWords = normalizedNewTitle.split(/\s+/);
      const matchingWords = newWords.filter(w => existingWords.has(w)).length;
      const similarity = matchingWords / Math.max(newWords.length, existingWords.size);

      if (similarity > 0.7) {
        return existingNote;
      }
    }

    return null;
  } catch (error) {
    console.error('[Case Notes] Error checking for duplicates:', error);
    return null;
  }
}

// Create new case note (with deduplication)
export async function createCaseNote(data: {
  title: string;
  clientId?: string; // Optional - may not always match a client
  date?: string;
  type: CaseNoteType;
  source: CaseNoteSource;
  fullNote?: string;
  content?: string; // Alias for fullNote
  autoGenerated?: boolean;
  skipDuplicateCheck?: boolean; // Set to true to bypass deduplication
  // Fireflies owner fields - to track who the meeting belongs to
  firefliesOwnerId?: string;
  firefliesOwnerEmail?: string;
}): Promise<CaseNote | null> {
  const noteContent = data.fullNote || data.content || '';
  const noteDate = data.date || new Date().toISOString().split('T')[0];

  // Check for duplicates if this is an auto-generated note
  if (data.autoGenerated && data.clientId && !data.skipDuplicateCheck) {
    const existing = await findSimilarCaseNote({
      clientId: data.clientId,
      title: data.title,
      date: noteDate,
      source: data.source,
    });

    if (existing) {
      console.log(`[Case Notes] Skipping duplicate: "${data.title}" - similar to existing "${existing.title}"`);
      return null; // Return null to indicate duplicate was skipped
    }
  }

  const properties: any = {
    'Note Title': { title: [{ text: { content: data.title } }] },
    'Type': { select: { name: data.type } },
    'Source': { select: { name: data.source } },
    'Full Note': { rich_text: [{ text: { content: noteContent.substring(0, 2000) } }] }, // Notion limit
  };

  // Only add client relation if clientId provided
  if (data.clientId) {
    properties['Client'] = { relation: [{ id: data.clientId }] };
  }

  if (data.date) {
    properties['Date'] = { date: { start: data.date } };
  }
  if (data.autoGenerated !== undefined) {
    properties['Auto-Generated'] = { checkbox: data.autoGenerated };
  }

  // Fireflies owner tracking - allows filtering case notes by owner
  if (data.firefliesOwnerId) {
    properties['Fireflies Owner ID'] = { rich_text: [{ text: { content: data.firefliesOwnerId } }] };
  }
  if (data.firefliesOwnerEmail) {
    properties['Fireflies Owner Email'] = { rich_text: [{ text: { content: data.firefliesOwnerEmail } }] };
  }

  const page = await notion.pages.create({
    parent: { database_id: DATABASE_IDS.caseNotes },
    properties,
  });

  return transformCaseNote(page);
}

// Update case note
export async function updateCaseNote(
  id: string,
  data: Partial<{
    title: string;
    type: CaseNoteType;
    source: CaseNoteSource;
    fullNote: string;
  }>
): Promise<CaseNote> {
  const properties: any = {};

  if (data.title) {
    properties['Note Title'] = { title: [{ text: { content: data.title } }] };
  }
  if (data.type) {
    properties['Type'] = { select: { name: data.type } };
  }
  if (data.source) {
    properties['Source'] = { select: { name: data.source } };
  }
  if (data.fullNote) {
    properties['Full Note'] = { rich_text: [{ text: { content: data.fullNote } }] };
  }

  const page = await notion.pages.update({
    page_id: id,
    properties,
  });

  return transformCaseNote(page);
}

// Get recent case notes (for dashboard)
export async function getRecentCaseNotes(limit: number = 5): Promise<CaseNote[]> {
  return getCaseNotes({ limit });
}

// Get case note stats for a client
export async function getCaseNoteStats(clientId: string): Promise<{
  total: number;
  byType: Record<CaseNoteType, number>;
  bySource: Record<CaseNoteSource, number>;
}> {
  const notes = await getClientCaseNotes(clientId);

  const byType: Record<CaseNoteType, number> = {
    'Internal Note': 0,
    'Client Request': 0,
    'Editing Guideline': 0,
  };

  const bySource: Record<CaseNoteSource, number> = {
    'Slack': 0,
    'Email': 0,
    'Call': 0,
    'Manual': 0,
  };

  notes.forEach((note) => {
    if (note.type && byType[note.type] !== undefined) {
      byType[note.type]++;
    }
    if (note.source && bySource[note.source] !== undefined) {
      bySource[note.source]++;
    }
  });

  return {
    total: notes.length,
    byType,
    bySource,
  };
}

// Delete a case note (archives it in Notion)
export async function deleteCaseNote(id: string): Promise<boolean> {
  try {
    await notion.pages.update({
      page_id: id,
      archived: true,
    });
    return true;
  } catch (error) {
    console.error('Failed to delete case note:', error);
    return false;
  }
}

// Delete multiple case notes
export async function deleteCaseNotes(ids: string[]): Promise<{ deleted: number; failed: number }> {
  let deleted = 0;
  let failed = 0;

  for (const id of ids) {
    const success = await deleteCaseNote(id);
    if (success) deleted++;
    else failed++;
  }

  return { deleted, failed };
}

// Get auto-generated Slack case notes (for cleanup)
export async function getAutoGeneratedSlackNotes(): Promise<CaseNote[]> {
  const response = await queryDatabase({
    database_id: DATABASE_IDS.caseNotes,
    filter: {
      and: [
        { property: 'Source', select: { equals: 'Slack' } },
        { property: 'Auto-Generated', checkbox: { equals: true } },
      ],
    },
    sorts: [{ property: 'Date', direction: 'descending' }],
    page_size: 100,
  });

  return response.results.map(transformCaseNote);
}

// Paginated case notes query with cursor support for "load more" functionality
export async function getCaseNotesPaginated(options?: {
  clientId?: string;
  type?: CaseNoteType;
  source?: CaseNoteSource;
  pageSize?: number;
  cursor?: string;
  // Fireflies owner filtering
  firefliesOwnerEmail?: string;
  firefliesOwnerEmails?: string[];
  includeNonFireflies?: boolean;
}): Promise<{
  caseNotes: CaseNote[];
  nextCursor: string | null;
  hasMore: boolean;
}> {
  try {
    const filters: any[] = [];

    if (options?.clientId) {
      filters.push({ property: 'Client', relation: { contains: options.clientId } });
    }
    if (options?.type) {
      filters.push({ property: 'Type', select: { equals: options.type } });
    }
    if (options?.source) {
      filters.push({ property: 'Source', select: { equals: options.source } });
    }

    // Filter by Fireflies owner email (single owner)
    if (options?.firefliesOwnerEmail) {
      filters.push({ property: 'Fireflies Owner Email', rich_text: { contains: options.firefliesOwnerEmail } });
    }

    // Filter by multiple Fireflies owner emails
    // If includeNonFireflies is true (Personal Brand team), also include notes without owner
    if (options?.firefliesOwnerEmails && options.firefliesOwnerEmails.length > 0) {
      const ownerFilters: any[] = options.firefliesOwnerEmails.map(email => ({
        property: 'Fireflies Owner Email',
        rich_text: { contains: email }, // Use contains for case-insensitive matching
      }));

      // Only include non-Fireflies notes (empty owner) if explicitly allowed
      if (options.includeNonFireflies) {
        ownerFilters.push({
          property: 'Fireflies Owner Email',
          rich_text: { is_empty: true },
        });
      }

      filters.push({ or: ownerFilters });
    } else if (options?.includeNonFireflies && !options?.firefliesOwnerEmails) {
      // Admin case: no email filter, but includeNonFireflies is true
      // This means show ALL notes (no filter needed)
    }

    const pageSize = options?.pageSize || 100;

    const response = await queryDatabase({
      database_id: DATABASE_IDS.caseNotes,
      filter: filters.length > 0 ? { and: filters } : undefined,
      sorts: [{ property: 'Date', direction: 'descending' }],
      page_size: Math.min(pageSize, 100),
      start_cursor: options?.cursor,
    });

    return {
      caseNotes: response.results.map(transformCaseNote),
      nextCursor: response.has_more ? (response.next_cursor as string) : null,
      hasMore: response.has_more,
    };
  } catch (error) {
    console.error('[Case Notes] Error in getCaseNotesPaginated:', error);
    throw error;
  }
}
