import { NextRequest, NextResponse } from 'next/server';
import { crawlChannelForNotes, findClientChannel, CrawlResult } from '@/lib/slack';
import { createCaseNote } from '@/lib/notion/case-notes';
import { getClient } from '@/lib/notion/clients';

// Storage for last crawl timestamps (in production, use a database)
const crawlState = new Map<string, { lastCrawl: Date; lastMessageTs?: string }>();

export interface CrawlResponse {
  ok: boolean;
  channelId?: string;
  channelName?: string;
  messagesProcessed?: number;
  caseNotesCreated?: number;
  actionItemsFound?: number;
  actionItems?: CrawlResult['actionItems'];
  caseNotes?: CrawlResult['caseNotes'];
  error?: string;
}

// POST /api/slack/crawl - Crawl a client's Slack channel for case notes
export async function POST(request: NextRequest): Promise<NextResponse<CrawlResponse>> {
  try {
    const body = await request.json();
    const { clientId, channelId, since, limit, saveCaseNotes = true } = body;

    if (!clientId && !channelId) {
      return NextResponse.json(
        { ok: false, error: 'Either clientId or channelId is required' },
        { status: 400 }
      );
    }

    let targetChannelId = channelId;
    let clientName: string | undefined;
    let actualClientId = clientId;

    // If clientId provided, get client info and find their channel
    if (clientId) {
      const client = await getClient(clientId);
      if (!client) {
        return NextResponse.json(
          { ok: false, error: 'Client not found' },
          { status: 404 }
        );
      }

      clientName = client.name;

      // Find client's Slack channel if not provided
      if (!targetChannelId) {
        const channelResult = await findClientChannel(client.name);
        if (!channelResult.ok || !channelResult.channel) {
          return NextResponse.json(
            { ok: false, error: `Could not find Slack channel for ${client.name}` },
            { status: 404 }
          );
        }
        targetChannelId = channelResult.channel.id;
      }
    }

    // Determine the "since" timestamp - either from request, from last crawl, or default to 7 days
    let sinceDate: Date | undefined;
    const stateKey = `${actualClientId || targetChannelId}`;

    if (since) {
      sinceDate = new Date(since);
    } else {
      const lastCrawlState = crawlState.get(stateKey);
      if (lastCrawlState?.lastCrawl) {
        sinceDate = lastCrawlState.lastCrawl;
      } else {
        // Default: 7 days ago for first crawl
        sinceDate = new Date();
        sinceDate.setDate(sinceDate.getDate() - 7);
      }
    }

    // Crawl the channel
    const crawlResult = await crawlChannelForNotes(targetChannelId, {
      since: sinceDate,
      limit: limit || 100,
      clientName,
    });

    if (!crawlResult.ok || !crawlResult.result) {
      return NextResponse.json(
        { ok: false, error: crawlResult.error || 'Crawl failed' },
        { status: 500 }
      );
    }

    const result = crawlResult.result;

    // Check if AI is available (required for quality case notes)
    const hasAnthropicKey = !!process.env.ANTHROPIC_API_KEY;

    // Update crawl state
    crawlState.set(stateKey, {
      lastCrawl: new Date(),
      lastMessageTs: result.lastMessageTimestamp,
    });

    // Save case notes to Notion if requested (with built-in deduplication)
    let caseNotesCreated = 0;
    if (saveCaseNotes && actualClientId && result.caseNotes.length > 0) {
      for (const note of result.caseNotes) {
        try {
          const caseNote = await createCaseNote({
            title: note.title,
            clientId: actualClientId,
            date: note.timestamp.toISOString().split('T')[0],
            type: note.type,
            source: 'Slack',
            fullNote: note.content,
            autoGenerated: true,
          });
          if (caseNote) caseNotesCreated++;
        } catch (err) {
          console.error('[Slack Crawl] Failed to create case note:', err);
        }
      }
    }

    return NextResponse.json({
      ok: true,
      channelId: result.channelId,
      channelName: result.channelName,
      messagesProcessed: result.messagesProcessed,
      caseNotesCreated,
      actionItemsFound: result.actionItems.length,
      actionItems: result.actionItems,
      caseNotes: result.caseNotes,
      // Inform if AI wasn't available
      aiEnabled: hasAnthropicKey,
      warning: !hasAnthropicKey && result.caseNotes.length === 0
        ? 'ANTHROPIC_API_KEY not configured. Slack crawler requires AI to produce quality case notes.'
        : undefined,
    });
  } catch (error) {
    console.error('Error crawling Slack channel:', error);
    return NextResponse.json(
      { ok: false, error: 'Failed to crawl channel' },
      { status: 500 }
    );
  }
}

// GET /api/slack/crawl - Get crawl status for a client
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const clientId = searchParams.get('clientId');
    const channelId = searchParams.get('channelId');

    if (!clientId && !channelId) {
      return NextResponse.json(
        { ok: false, error: 'Either clientId or channelId is required' },
        { status: 400 }
      );
    }

    const stateKey = clientId || channelId;
    const state = crawlState.get(stateKey!);

    if (!state) {
      return NextResponse.json({
        ok: true,
        hasCrawled: false,
        message: 'No previous crawl recorded for this client/channel',
      });
    }

    return NextResponse.json({
      ok: true,
      hasCrawled: true,
      lastCrawl: state.lastCrawl.toISOString(),
      lastMessageTs: state.lastMessageTs,
    });
  } catch (error) {
    console.error('Error getting crawl status:', error);
    return NextResponse.json(
      { ok: false, error: 'Failed to get crawl status' },
      { status: 500 }
    );
  }
}
