import { NextRequest, NextResponse } from 'next/server';
import { getAutoGeneratedSlackNotes, deleteCaseNotes } from '@/lib/notion/case-notes';

// DELETE /api/slack/cleanup - Delete all auto-generated Slack case notes
// This is useful for cleaning up old low-quality notes after improving the crawler
export async function DELETE(request: NextRequest) {
  try {
    // Get all auto-generated Slack notes
    const slackNotes = await getAutoGeneratedSlackNotes();

    if (slackNotes.length === 0) {
      return NextResponse.json({
        success: true,
        message: 'No auto-generated Slack case notes found',
        deleted: 0,
      });
    }

    // Delete all of them
    const noteIds = slackNotes.map(note => note.id);
    const result = await deleteCaseNotes(noteIds);

    console.log(`[Slack Cleanup] Deleted ${result.deleted} case notes, ${result.failed} failed`);

    return NextResponse.json({
      success: true,
      message: `Deleted ${result.deleted} auto-generated Slack case notes`,
      deleted: result.deleted,
      failed: result.failed,
      noteIds: noteIds,
    });
  } catch (error) {
    console.error('[Slack Cleanup] Error:', error);
    return NextResponse.json(
      { error: 'Failed to cleanup Slack case notes' },
      { status: 500 }
    );
  }
}

// GET /api/slack/cleanup - Preview auto-generated Slack case notes that would be deleted
export async function GET() {
  try {
    const slackNotes = await getAutoGeneratedSlackNotes();

    return NextResponse.json({
      count: slackNotes.length,
      notes: slackNotes.map(note => ({
        id: note.id,
        title: note.title,
        date: note.date,
        clientId: note.clientId,
        type: note.type,
      })),
    });
  } catch (error) {
    console.error('[Slack Cleanup] Error:', error);
    return NextResponse.json(
      { error: 'Failed to get Slack case notes' },
      { status: 500 }
    );
  }
}
