import { NextRequest, NextResponse } from 'next/server';
import { crawlChannelForNotes, findClientChannel, sendChannelNotification, extractChannelId, getChannelInfo } from '@/lib/slack';
import { createCaseNote } from '@/lib/notion/case-notes';
import { getClients } from '@/lib/notion/clients';

// Track last crawl time per client for incremental crawling
// In production, this should be stored in a database
const lastCrawlTimes = new Map<string, Date>();

// Default lookback period for first-time crawls (24 hours)
const DEFAULT_LOOKBACK_HOURS = 24;

// POST /api/slack/crawl/scheduled - Run scheduled crawl for all active clients
// This endpoint can be called by Vercel Cron or any scheduled job
export async function POST(request: NextRequest) {
  try {
    // Verify cron secret for security (optional but recommended)
    const authHeader = request.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;

    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Get all active clients
    const clients = await getClients('Active');

    const results: Array<{
      clientId: string;
      clientName: string;
      status: 'success' | 'skipped' | 'error';
      channelName?: string;
      messagesProcessed?: number;
      caseNotesCreated?: number;
      tasksCreated?: number;
      error?: string;
    }> = [];

    for (const client of clients) {
      try {
        let channelId: string | null = null;
        let channelName: string | undefined;

        // First, check if client has a stored Slack channel URL
        if (client.slackChannel) {
          channelId = extractChannelId(client.slackChannel);
          if (channelId) {
            const channelInfo = await getChannelInfo(channelId);
            if (channelInfo.ok && channelInfo.channel) {
              channelName = channelInfo.channel.name;
            }
          }
        }

        // Fall back to searching by client name if no stored channel
        if (!channelId) {
          const channelResult = await findClientChannel(client.name);
          if (channelResult.ok && channelResult.channel) {
            channelId = channelResult.channel.id;
            channelName = channelResult.channel.name;
          }
        }

        if (!channelId) {
          results.push({
            clientId: client.id,
            clientName: client.name,
            status: 'skipped',
            error: 'No Slack channel configured or found',
          });
          continue;
        }

        // Calculate since date (last crawl or default lookback)
        const lastCrawl = lastCrawlTimes.get(client.id);
        const sinceDate = lastCrawl || new Date(Date.now() - DEFAULT_LOOKBACK_HOURS * 60 * 60 * 1000);

        // Crawl the channel
        const crawlResult = await crawlChannelForNotes(channelId, {
          since: sinceDate,
          limit: 50, // Limit per crawl to avoid overwhelming
          clientName: client.name,
        });

        if (!crawlResult.ok || !crawlResult.result) {
          results.push({
            clientId: client.id,
            clientName: client.name,
            status: 'error',
            channelName,
            error: crawlResult.error || 'Crawl failed',
          });
          continue;
        }

        const result = crawlResult.result;

        // Update last crawl time
        lastCrawlTimes.set(client.id, new Date());

        // Skip if no new content
        if (result.caseNotes.length === 0 && result.actionItems.length === 0) {
          results.push({
            clientId: client.id,
            clientName: client.name,
            status: 'success',
            channelName,
            messagesProcessed: result.messagesProcessed,
            caseNotesCreated: 0,
            tasksCreated: 0,
          });
          continue;
        }

        // Create case notes (with built-in deduplication)
        // Note: Tasks are NOT automatically created - users must manually create them from the case notes UI
        let caseNotesCreated = 0;
        for (const note of result.caseNotes) {
          try {
            const caseNote = await createCaseNote({
              title: note.title,
              clientId: client.id,
              type: note.type,
              source: 'Slack',
              date: note.timestamp.toISOString().split('T')[0],
              content: `From ${note.author}:\n\n${note.content}`,
              autoGenerated: true,
            });
            if (caseNote) caseNotesCreated++;
          } catch (err) {
            console.error(`[Scheduled Crawl] Failed to create case note for ${client.name}:`, err);
          }
        }

        // Tasks are NOT auto-created from action items anymore
        // Users should manually create tasks from the case notes tab with proper assignee selection
        // Action items are included in the case note content for reference
        const tasksCreated = 0;

        results.push({
          clientId: client.id,
          clientName: client.name,
          status: 'success',
          channelName,
          messagesProcessed: result.messagesProcessed,
          caseNotesCreated,
          tasksCreated,
        });
      } catch (error) {
        results.push({
          clientId: client.id,
          clientName: client.name,
          status: 'error',
          error: String(error),
        });
      }
    }

    // Calculate summary
    const summary = {
      totalClients: results.length,
      successful: results.filter(r => r.status === 'success').length,
      skipped: results.filter(r => r.status === 'skipped').length,
      errors: results.filter(r => r.status === 'error').length,
      totalCaseNotes: results.reduce((acc, r) => acc + (r.caseNotesCreated || 0), 0),
      totalTasks: results.reduce((acc, r) => acc + (r.tasksCreated || 0), 0),
    };

    // Send summary notification to Slack if there's new content
    if (summary.totalCaseNotes > 0 || summary.totalTasks > 0) {
      await sendChannelNotification(
        'Slack Crawl Complete',
        `Crawled ${summary.successful} client channels\n` +
        `• ${summary.totalCaseNotes} new case notes captured\n` +
        `• ${summary.totalTasks} new tasks created`,
        'info'
      );
    }

    return NextResponse.json({
      success: true,
      summary,
      results,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Error in scheduled crawl:', error);
    return NextResponse.json(
      { error: 'Scheduled crawl failed' },
      { status: 500 }
    );
  }
}

// GET /api/slack/crawl/scheduled - Get scheduled crawl status
export async function GET() {
  const crawlStatus = Array.from(lastCrawlTimes.entries()).map(([clientId, lastCrawl]) => ({
    clientId,
    lastCrawl: lastCrawl.toISOString(),
  }));

  return NextResponse.json({
    status: 'ready',
    clientsTracked: crawlStatus.length,
    lastCrawls: crawlStatus,
    defaultLookbackHours: DEFAULT_LOOKBACK_HOURS,
  });
}
