'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Client, ContentType, Idea } from '@/types';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Plus, Loader2, AlertTriangle, Link, Sparkles, ChevronDown, ChevronUp } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface NewIdeaDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  clients: Client[];
  onIdeaCreated: (idea: Idea) => void;
  defaultContentType?: ContentType;
}

export function NewIdeaDialog({
  open,
  onOpenChange,
  clients,
  onIdeaCreated,
  defaultContentType,
}: NewIdeaDialogProps) {
  const router = useRouter();
  const [title, setTitle] = useState('');
  const [clientId, setClientId] = useState('');
  const [contentType, setContentType] = useState<ContentType>(defaultContentType || 'Short Form');
  const [angle, setAngle] = useState('');
  const [angleInstructions, setAngleInstructions] = useState('');
  const [showAngleInstructions, setShowAngleInstructions] = useState(false);
  const [isGeneratingAngle, setIsGeneratingAngle] = useState(false);
  const [hook, setHook] = useState('');
  const [script, setScript] = useState('');
  const [source, setSource] = useState('');
  const [sourceLink, setSourceLink] = useState('');
  const [briefUrl, setBriefUrl] = useState('');
  const [editingNotes, setEditingNotes] = useState('');
  const [isUrgent, setIsUrgent] = useState(false);
  const [isCreating, setIsCreating] = useState(false);

  // Generate angle using Claude
  const handleGenerateAngle = async () => {
    if (!title.trim()) {
      toast.error('Please enter a title first');
      return;
    }

    setIsGeneratingAngle(true);
    try {
      const selectedClient = clients.find(c => c.id === clientId);
      const response = await fetch('/api/ideas/generate-angle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title.trim(),
          clientName: selectedClient?.name,
          contentType,
          hook: hook.trim() || undefined,
          script: script.trim() || undefined,
          source: source || undefined,
          sourceLink: sourceLink.trim() || undefined,
          instructions: angleInstructions.trim() || undefined,
        }),
      });

      if (!response.ok) throw new Error('Failed to generate angle');

      const data = await response.json();
      setAngle(data.angle);
      toast.success('Angle generated by Claude');
    } catch (error) {
      toast.error('Failed to generate angle');
      console.error('Error generating angle:', error);
    } finally {
      setIsGeneratingAngle(false);
    }
  };

  const handleCreate = async () => {
    if (!title.trim() || !clientId) return;

    setIsCreating(true);
    try {
      const response = await fetch('/api/ideas', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title.trim(),
          clientId,
          contentType,
          status: 'Not started',
          priority: isUrgent ? 'Urgent' : 'Not Urgent',
          angle: angle.trim() || undefined,
          hook: hook.trim() || undefined,
          script: script.trim() || undefined,
          source: source || undefined,
          sourceLink: sourceLink.trim() || undefined,
          briefUrl: briefUrl.trim() || undefined,
          editingNotes: editingNotes.trim() || undefined,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        console.error('Create idea error:', data);
        throw new Error(data.details || 'Failed to create idea');
      }

      toast.success('Idea created successfully');
      router.refresh();
      onIdeaCreated(data);
      onOpenChange(false);
      // Reset form
      setTitle('');
      setAngle('');
      setAngleInstructions('');
      setShowAngleInstructions(false);
      setHook('');
      setScript('');
      setSource('');
      setSourceLink('');
      setBriefUrl('');
      setEditingNotes('');
      setClientId('');
      setIsUrgent(false);
    } catch (error) {
      toast.error('Failed to create idea');
      console.error('Error creating idea:', error);
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-zinc-900 border-zinc-800 max-w-lg max-h-[90vh] flex flex-col">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle className="text-white">New Idea</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4 overflow-y-auto flex-1 pr-2">
          <div className="space-y-2">
            <Label className="text-zinc-300">Title *</Label>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Idea title or topic..."
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-zinc-300">Client *</Label>
              <Select value={clientId} onValueChange={setClientId}>
                <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                  <SelectValue placeholder="Select client..." />
                </SelectTrigger>
                <SelectContent className="bg-zinc-800 border-zinc-700">
                  {clients.map((client) => (
                    <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-zinc-300">Content Type</Label>
              <Select value={contentType} onValueChange={(v) => setContentType(v as ContentType)}>
                <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-zinc-800 border-zinc-700">
                  <SelectItem value="Short Form">Short Form</SelectItem>
                  <SelectItem value="YouTube">YouTube</SelectItem>
                  <SelectItem value="Podcast">Podcast</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label className="text-zinc-300 flex items-center gap-2">
                Angle
                <span className="text-xs text-zinc-500">(Created by Claude)</span>
              </Label>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleGenerateAngle}
                disabled={isGeneratingAngle || !title.trim()}
                className="h-7 gap-1.5 border-purple-500/30 text-purple-400 hover:bg-purple-500/10"
              >
                {isGeneratingAngle ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5" />
                    Generate with Claude
                  </>
                )}
              </Button>
            </div>
            <Textarea
              value={angle}
              onChange={(e) => setAngle(e.target.value)}
              placeholder="The angle or perspective for this content..."
              className="bg-zinc-800 border-zinc-700 text-white min-h-[60px]"
            />

            {/* Claude Instructions Toggle */}
            <button
              type="button"
              onClick={() => setShowAngleInstructions(!showAngleInstructions)}
              className="flex items-center gap-1 text-xs text-zinc-500 hover:text-zinc-400 transition-colors"
            >
              {showAngleInstructions ? (
                <ChevronUp className="w-3 h-3" />
              ) : (
                <ChevronDown className="w-3 h-3" />
              )}
              Add instructions for Claude (optional)
            </button>

            {showAngleInstructions && (
              <Textarea
                value={angleInstructions}
                onChange={(e) => setAngleInstructions(e.target.value)}
                placeholder="E.g., 'Focus on controversial takes', 'Make it educational', 'Target beginners'..."
                className="bg-zinc-800/50 border-zinc-700 text-white min-h-[50px] text-sm"
              />
            )}
          </div>

          <div className="space-y-2">
            <Label className="text-zinc-300">Hook</Label>
            <Input
              value={hook}
              onChange={(e) => setHook(e.target.value)}
              placeholder="Opening hook..."
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="space-y-2">
            <Label className="text-zinc-300">Script/Notes</Label>
            <Textarea
              value={script}
              onChange={(e) => setScript(e.target.value)}
              placeholder="Script or notes..."
              className="bg-zinc-800 border-zinc-700 text-white min-h-[80px]"
            />
          </div>

          <div className="space-y-2">
            <Label className="text-zinc-300">Source</Label>
            <Select value={source} onValueChange={setSource}>
              <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                <SelectValue placeholder="Select source..." />
              </SelectTrigger>
              <SelectContent className="bg-zinc-800 border-zinc-700">
                <SelectItem value="Brainstorm">Brainstorm</SelectItem>
                <SelectItem value="Article">Article</SelectItem>
                <SelectItem value="Reddit">Reddit</SelectItem>
                <SelectItem value="YouTube">YouTube</SelectItem>
                <SelectItem value="TikTok">TikTok</SelectItem>
                <SelectItem value="X">X</SelectItem>
                <SelectItem value="Facebook">Facebook</SelectItem>
                <SelectItem value="Reels">Reels</SelectItem>
                <SelectItem value="Question">Question</SelectItem>
                <SelectItem value="Email">Email</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label className="text-zinc-300 flex items-center gap-2">
              <Link className="w-4 h-4" />
              Source Link
              <span className="text-zinc-500 text-xs">(optional)</span>
            </Label>
            <Input
              value={sourceLink}
              onChange={(e) => setSourceLink(e.target.value)}
              placeholder="https://..."
              type="url"
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="space-y-2">
            <Label className="text-zinc-300 flex items-center gap-2">
              <Link className="w-4 h-4" />
              Brief Link
              <span className="text-zinc-500 text-xs">(optional)</span>
            </Label>
            <Input
              value={briefUrl}
              onChange={(e) => setBriefUrl(e.target.value)}
              placeholder="https://..."
              type="url"
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          <div className="space-y-2">
            <Label className="text-zinc-300">
              Editing Notes
              <span className="text-zinc-500 text-xs ml-2">(internal - carries over to pipeline)</span>
            </Label>
            <Textarea
              value={editingNotes}
              onChange={(e) => setEditingNotes(e.target.value)}
              placeholder="Notes for editors when this becomes content..."
              className="bg-zinc-800 border-zinc-700 text-white min-h-[60px]"
            />
          </div>

          {/* Urgent Toggle */}
          <div
            className={cn(
              "flex items-center justify-between p-3 rounded-lg border transition-colors",
              isUrgent
                ? "bg-red-950/30 border-red-500/50"
                : "bg-zinc-800/50 border-zinc-700"
            )}
          >
            <div className="flex items-center gap-3">
              <AlertTriangle className={cn(
                "w-5 h-5",
                isUrgent ? "text-red-500" : "text-zinc-500"
              )} />
              <div>
                <Label className={cn(
                  "font-medium",
                  isUrgent ? "text-red-400" : "text-zinc-300"
                )}>
                  Mark as Urgent
                </Label>
                <p className="text-xs text-zinc-500">
                  Sends alert to team for immediate action
                </p>
              </div>
            </div>
            <Switch
              checked={isUrgent}
              onCheckedChange={setIsUrgent}
              className="data-[state=checked]:bg-red-500"
            />
          </div>
        </div>

        <DialogFooter className="flex-shrink-0 border-t border-zinc-800 pt-4">
          <Button variant="outline" onClick={() => onOpenChange(false)} className="border-zinc-700">
            Cancel
          </Button>
          <Button onClick={handleCreate} disabled={!title.trim() || !clientId || isCreating}>
            {isCreating ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Plus className="w-4 h-4 mr-2" />}
            Create Idea
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
