import { NextRequest, NextResponse } from 'next/server';
import {
  parseTranscript,
  parseFirefliesPayload,
  FirefliesWebhookPayload,
} from '@/lib/integrations/notetaker';
import { createCaseNote } from '@/lib/notion/case-notes';
import { createTask } from '@/lib/notion/tasks';
import { getClients } from '@/lib/notion/clients';

/**
 * Fireflies.ai Webhook Endpoint
 *
 * To set up:
 * 1. Go to Fireflies.ai Settings > Integrations > Webhooks
 * 2. Add webhook URL: https://your-domain.com/api/notetaker/webhook/fireflies
 * 3. Select events: meeting_ended, transcript_ready
 * 4. Save
 *
 * The webhook will automatically create case notes and tasks from meeting transcripts.
 */

// Verify Fireflies webhook signature (optional but recommended)
function verifyFirefliesSignature(
  payload: string,
  signature: string | null,
  secret: string | null
): boolean {
  if (!secret || !signature) {
    // If no secret configured, skip verification
    return true;
  }

  // Fireflies uses HMAC SHA-256 for webhook signatures
  // Implement verification if you have a webhook secret configured
  return true;
}

export async function POST(request: NextRequest) {
  try {
    const webhookSecret = process.env.FIREFLIES_WEBHOOK_SECRET;
    const signature = request.headers.get('x-fireflies-signature');
    const rawBody = await request.text();

    // Verify webhook signature
    if (!verifyFirefliesSignature(rawBody, signature, webhookSecret || null)) {
      return NextResponse.json(
        { error: 'Invalid webhook signature' },
        { status: 401 }
      );
    }

    const payload: FirefliesWebhookPayload = JSON.parse(rawBody);

    // Skip if no transcript available
    if (!payload.transcript?.text) {
      return NextResponse.json({
        success: true,
        message: 'No transcript in payload, skipping',
      });
    }

    // Parse the Fireflies payload
    const transcript = parseFirefliesPayload(payload);
    const parsedNote = parseTranscript(transcript);

    // Try to match client from participants or title
    let clientId: string | undefined;
    if (parsedNote.clientName) {
      const clients = await getClients();
      const matchedClient = clients.find(
        c =>
          c.name.toLowerCase().includes(parsedNote.clientName!.toLowerCase()) ||
          parsedNote.clientName!.toLowerCase().includes(c.name.toLowerCase())
      );
      if (matchedClient) {
        clientId = matchedClient.id;
      }
    }

    // Create case note
    const caseNote = await createCaseNote({
      title: `[Meeting] ${parsedNote.title}`,
      clientId,
      type: parsedNote.type,
      source: 'Call',
      date: parsedNote.date,
      content: `Meeting recorded via Fireflies.ai\n\n${parsedNote.content}\n\n---\nParticipants: ${payload.participants.map(p => p.name).join(', ')}${payload.meeting_link ? `\nMeeting Link: ${payload.meeting_link}` : ''}`,
      autoGenerated: true,
    });

    if (!caseNote) {
      return NextResponse.json({
        success: true,
        caseNoteId: null,
        tasksCreated: 0,
        clientMatched: !!clientId,
        message: 'Duplicate case note detected, skipped creation',
      });
    }

    // Create tasks from action items
    const createdTasks: string[] = [];
    if (clientId && parsedNote.actionItems.length > 0) {
      for (const actionItem of parsedNote.actionItems) {
        try {
          const task = await createTask({
            task: actionItem.task,
            clientId,
            status: 'To Do',
            urgency: actionItem.urgency,
            sourceCaseNoteId: caseNote.id,
            notes: `Auto-generated from Fireflies meeting: ${payload.title}`,
          });
          if (task) {
            createdTasks.push(task.id);
          }
        } catch (error) {
          console.error('Failed to create task from Fireflies:', error);
        }
      }
    }

    console.log(`[Fireflies Webhook] Created case note ${caseNote.id} with ${createdTasks.length} tasks`);

    return NextResponse.json({
      success: true,
      caseNoteId: caseNote.id,
      tasksCreated: createdTasks.length,
      clientMatched: !!clientId,
    });
  } catch (error) {
    console.error('Fireflies webhook error:', error);
    return NextResponse.json(
      { error: 'Failed to process Fireflies webhook' },
      { status: 500 }
    );
  }
}

// GET endpoint for webhook verification (some services ping with GET first)
export async function GET() {
  return NextResponse.json({
    status: 'ok',
    service: 'Fireflies Webhook',
    message: 'Webhook endpoint is active',
  });
}
