'use client';

import { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Loader2, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { CaseNoteType, CaseNoteSource, Client } from '@/types';

interface AddCaseNoteDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  clientId?: string;
  clientName?: string;
  clients?: Client[];
  onNoteCreated?: () => void;
}

export function AddCaseNoteDialog({
  open,
  onOpenChange,
  clientId: initialClientId,
  clientName: initialClientName,
  clients: providedClients,
  onNoteCreated,
}: AddCaseNoteDialogProps) {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [type, setType] = useState<CaseNoteType>('Internal Note');
  const [source, setSource] = useState<CaseNoteSource>('Manual');
  const [isCreating, setIsCreating] = useState(false);
  const [selectedClientId, setSelectedClientId] = useState(initialClientId || '');
  const [clients, setClients] = useState<Client[]>(providedClients || []);
  const [loadingClients, setLoadingClients] = useState(false);

  // Fetch clients if not provided
  useEffect(() => {
    if (open && !providedClients && clients.length === 0) {
      setLoadingClients(true);
      fetch('/api/clients?status=Active')
        .then(res => res.json())
        .then(data => {
          setClients(data);
          if (!selectedClientId && data.length > 0) {
            setSelectedClientId(data[0].id);
          }
        })
        .catch(console.error)
        .finally(() => setLoadingClients(false));
    }
  }, [open, providedClients, clients.length, selectedClientId]);

  // Update selected client when initial value changes
  useEffect(() => {
    if (initialClientId) {
      setSelectedClientId(initialClientId);
    }
  }, [initialClientId]);

  const resetForm = () => {
    setTitle('');
    setContent('');
    setType('Internal Note');
    setSource('Manual');
    if (!initialClientId && clients.length > 0) {
      setSelectedClientId(clients[0].id);
    }
  };

  const handleClose = () => {
    resetForm();
    onOpenChange(false);
  };

  const handleSubmit = async () => {
    if (!title.trim() || !content.trim()) {
      toast.error('Please fill in title and note content');
      return;
    }

    if (!selectedClientId) {
      toast.error('Please select a client');
      return;
    }

    setIsCreating(true);

    try {
      const response = await fetch('/api/case-notes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title.trim(),
          clientId: selectedClientId,
          type,
          source,
          fullNote: content.trim(),
          date: new Date().toISOString().split('T')[0],
          autoGenerated: false,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to create case note');
      }

      toast.success('Case note added');
      onNoteCreated?.();
      handleClose();
    } catch (error) {
      toast.error('Failed to add case note');
      console.error('Error creating case note:', error);
    } finally {
      setIsCreating(false);
    }
  };

  const getSelectedClientName = () => {
    if (initialClientName && selectedClientId === initialClientId) {
      return initialClientName;
    }
    const client = clients.find(c => c.id === selectedClientId);
    return client?.name || 'Select a client';
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="bg-zinc-900 border-zinc-800 max-w-lg">
        <DialogHeader>
          <DialogTitle className="text-white">Add Case Note</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Client Selector */}
          {initialClientId && initialClientName ? (
            <div className="p-3 rounded-lg bg-zinc-800 border border-zinc-700">
              <p className="text-xs text-zinc-500 mb-1">Adding note for</p>
              <p className="text-sm font-medium text-white">{initialClientName}</p>
            </div>
          ) : (
            <div className="space-y-2">
              <Label className="text-zinc-300">Client</Label>
              <Select
                value={selectedClientId}
                onValueChange={setSelectedClientId}
                disabled={loadingClients}
              >
                <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                  <SelectValue placeholder={loadingClients ? 'Loading...' : 'Select a client'} />
                </SelectTrigger>
                <SelectContent className="bg-zinc-800 border-zinc-700">
                  {clients.map(client => (
                    <SelectItem key={client.id} value={client.id}>
                      {client.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {/* Title */}
          <div className="space-y-2">
            <Label htmlFor="title" className="text-zinc-300">Title</Label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., Client prefers shorter intros"
              className="bg-zinc-800 border-zinc-700 text-white"
            />
          </div>

          {/* Type and Source Row */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-zinc-300">Type</Label>
              <Select value={type} onValueChange={(v) => setType(v as CaseNoteType)}>
                <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-zinc-800 border-zinc-700">
                  <SelectItem value="Internal Note">Internal Note</SelectItem>
                  <SelectItem value="Client Request">Client Request</SelectItem>
                  <SelectItem value="Editing Guideline">Editing Guideline</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-zinc-300">Source</Label>
              <Select value={source} onValueChange={(v) => setSource(v as CaseNoteSource)}>
                <SelectTrigger className="bg-zinc-800 border-zinc-700 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-zinc-800 border-zinc-700">
                  <SelectItem value="Manual">Manual</SelectItem>
                  <SelectItem value="Call">Call</SelectItem>
                  <SelectItem value="Email">Email</SelectItem>
                  <SelectItem value="Slack">Slack</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Note Content */}
          <div className="space-y-2">
            <Label htmlFor="content" className="text-zinc-300">Note</Label>
            <Textarea
              id="content"
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Enter the case note details..."
              className="bg-zinc-800 border-zinc-700 text-white min-h-[120px]"
            />
          </div>
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={handleClose}
            className="border-zinc-700 text-zinc-300"
          >
            Cancel
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={!title.trim() || !content.trim() || isCreating}
            className="gap-2"
          >
            {isCreating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Adding...
              </>
            ) : (
              <>
                <Plus className="w-4 h-4" />
                Add Note
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
