import { NextRequest, NextResponse } from 'next/server';
import { createCaseNote } from '@/lib/notion/case-notes';
import { getClients } from '@/lib/notion/clients';
import {
  categorizeMessage,
  shouldCaptureCaseNote,
  extractUrgency,
  generateCaseNoteTitle,
  extractClientFromChannel,
  SlackEvent,
} from '@/lib/slack';

// Slack webhook endpoint for Events API
export async function POST(request: NextRequest) {
  try {
    const body = await request.text();
    const payload = JSON.parse(body) as SlackEvent;

    // Handle URL verification challenge (required by Slack)
    if (payload.type === 'url_verification') {
      return NextResponse.json({ challenge: payload.challenge });
    }

    // Handle event callbacks
    if (payload.type === 'event_callback') {
      const event = payload.event;

      // Only process message events
      if (event.type !== 'message') {
        return NextResponse.json({ ok: true });
      }

      // Skip bot messages and message edits
      if (event.user?.startsWith('B') || !event.text) {
        return NextResponse.json({ ok: true });
      }

      // Check if this message should be captured
      if (!shouldCaptureCaseNote(event.text)) {
        return NextResponse.json({ ok: true });
      }

      // Process the message asynchronously
      processSlackMessage(event, payload.team_id).catch((err) => {
        console.error('Error processing Slack message:', err);
      });

      // Return immediately (Slack expects quick response)
      return NextResponse.json({ ok: true });
    }

    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error('Slack webhook error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

async function processSlackMessage(
  event: SlackEvent['event'],
  teamId: string
) {
  try {
    // Get channel info to find client
    const channelName = await getChannelName(event.channel);
    if (!channelName) {
      console.log('Could not get channel name for:', event.channel);
      return;
    }

    // Try to match channel to a client
    const clientName = extractClientFromChannel(channelName);
    const clients = await getClients('Active');

    const matchedClient = clients.find((c) => {
      const normalizedClientName = c.name.toLowerCase().replace(/\s+/g, '');
      const normalizedChannelClient = clientName?.toLowerCase().replace(/\s+/g, '') || '';
      return (
        normalizedClientName.includes(normalizedChannelClient) ||
        normalizedChannelClient.includes(normalizedClientName)
      );
    });

    if (!matchedClient) {
      console.log(`No matching client found for channel: ${channelName}`);
      return;
    }

    // Categorize the message
    const noteType = categorizeMessage(event.text);
    const urgency = extractUrgency(event.text);
    const title = generateCaseNoteTitle(event.text);

    // Create the case note
    await createCaseNote({
      title,
      clientId: matchedClient.id,
      date: new Date().toISOString().split('T')[0],
      type: noteType,
      source: 'Slack',
      fullNote: event.text,
      autoGenerated: true,
    });

    console.log(`Created case note for ${matchedClient.name}: ${title}`);

    // If it's a client request with urgency, auto-create a task
    if (noteType === 'Client Request' && urgency === 'Urgent') {
      // Task will be created via the case-note-to-task flow
      console.log(`Urgent request detected, task creation recommended`);
    }
  } catch (error) {
    console.error('Error processing Slack message:', error);
  }
}

// Get channel name from Slack API
async function getChannelName(channelId: string): Promise<string | null> {
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) {
    console.error('SLACK_BOT_TOKEN not configured');
    return null;
  }

  try {
    const response = await fetch(`https://slack.com/api/conversations.info?channel=${channelId}`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    const data = await response.json();
    if (data.ok) {
      return data.channel?.name || null;
    }

    console.error('Slack API error:', data.error);
    return null;
  } catch (error) {
    console.error('Error fetching channel info:', error);
    return null;
  }
}
