import { getClients } from '@/lib/notion/clients';
import { getCaseNotes } from '@/lib/notion/case-notes';
import { NotetakerAgentDashboard } from '@/components/agents/notetaker-dashboard';

export const dynamic = 'force-dynamic';

async function getAgentData() {
  const [clients, recentNotes] = await Promise.all([
    getClients('Active'),
    getCaseNotes({ limit: 50 }),
  ]);

  // Filter for auto-generated notes in the last 24 hours
  const oneDayAgo = new Date();
  oneDayAgo.setDate(oneDayAgo.getDate() - 1);

  const recentAutoNotes = recentNotes.filter(
    (note) => note.autoGenerated && new Date(note.date) > oneDayAgo
  );

  // Count by source
  const sourceStats = {
    slack: recentAutoNotes.filter((n) => n.source === 'Slack').length,
    email: recentAutoNotes.filter((n) => n.source === 'Email').length,
    call: recentAutoNotes.filter((n) => n.source === 'Call').length,
  };

  // Clients with Slack channels configured
  const clientsWithSlack = clients.filter((c) => c.slackChannel);

  return {
    clients,
    clientsWithSlack,
    recentAutoNotes,
    sourceStats,
  };
}

export default async function NotetakerAgentPage() {
  const data = await getAgentData();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Notetaker Agent</h1>
        <p className="text-zinc-400">
          Automated case note extraction from Slack, Email, and Meeting transcripts
        </p>
      </div>

      <NotetakerAgentDashboard
        clients={data.clients}
        clientsWithSlack={data.clientsWithSlack}
        recentAutoNotes={data.recentAutoNotes}
        sourceStats={data.sourceStats}
      />
    </div>
  );
}
