import { NextRequest, NextResponse } from 'next/server';
import {
  parseTranscript,
  parseTranscriptEnhanced,
  parseFirefliesPayload,
  parseFathomPayload,
  parseManualInput,
  parseSlackMessages,
  parseEmailThread,
  MeetingTranscript,
  FirefliesWebhookPayload,
  FathomPayload,
  ManualTranscriptInput,
  SlackMessageInput,
  EmailThreadInput,
} from '@/lib/integrations/notetaker';
import { createCaseNote } from '@/lib/notion/case-notes';
import { createTask } from '@/lib/notion/tasks';
import { getClients } from '@/lib/notion/clients';
import {
  fetchChannelMessagesForProcessing,
  filterActionableMessages,
  crawlChannelForNotes,
  extractChannelId,
} from '@/lib/slack';

// Handler for extracting notes from a Slack channel directly using AI-powered crawler
async function handleSlackChannelExtraction(
  payload: {
    channelUrl: string;
    clientId?: string;
    clientName?: string;
    limit?: number;
    sinceDays?: number;
    filterActionable?: boolean;
  },
  createTasksFromNotes: boolean,
  useAI: boolean = true
): Promise<NextResponse> {
  const { channelUrl, clientId, clientName, limit = 100, sinceDays = 7 } = payload;

  if (!channelUrl) {
    return NextResponse.json(
      { error: 'channelUrl is required for slack-channel source' },
      { status: 400 }
    );
  }

  // Extract channel ID from URL
  const channelId = extractChannelId(channelUrl);
  if (!channelId) {
    return NextResponse.json(
      { error: 'Invalid Slack channel URL' },
      { status: 400 }
    );
  }

  // Calculate since date
  const since = new Date();
  since.setDate(since.getDate() - sinceDays);

  // Use AI-powered crawler
  const crawlResult = await crawlChannelForNotes(channelId, {
    since,
    limit,
    clientName,
  });

  if (!crawlResult.ok || !crawlResult.result) {
    return NextResponse.json(
      { error: crawlResult.error || 'Failed to crawl Slack channel' },
      { status: 500 }
    );
  }

  const result = crawlResult.result;

  if (result.caseNotes.length === 0 && result.actionItems.length === 0) {
    return NextResponse.json({
      success: true,
      message: 'No notable messages found in the channel',
      messagesScanned: result.messagesProcessed,
      caseNotesCreated: 0,
      tasksCreated: 0,
    });
  }

  // Create case notes from AI-extracted notes
  const createdNotes: Array<{ id: string; title: string }> = [];
  const createdTasks: Array<{ id: string; task: string }> = [];

  for (const note of result.caseNotes) {
    try {
      const caseNote = await createCaseNote({
        title: note.title,
        clientId,
        type: note.type,
        source: 'Slack',
        date: note.timestamp.toISOString().split('T')[0],
        content: `From ${note.author}:\n\n${note.content}`,
        autoGenerated: true,
      });

      if (caseNote) {
        createdNotes.push({ id: caseNote.id, title: caseNote.title });
      }
    } catch (noteError) {
      console.error('Failed to create case note:', noteError);
    }
  }

  // Create tasks from action items if enabled
  if (createTasksFromNotes && clientId) {
    for (const item of result.actionItems) {
      try {
        const task = await createTask({
          task: item.task,
          clientId,
          status: 'To Do',
          urgency: item.urgency,
          notes: `Auto-generated from Slack (${item.assignee ? `assigned to ${item.assignee}` : 'no assignee'})`,
        });
        if (task) {
          createdTasks.push({ id: task.id, task: task.task });
        }
      } catch (taskError) {
        console.error('Failed to create task from action item:', taskError);
      }
    }
  }

  return NextResponse.json({
    success: true,
    channelName: result.channelName,
    messagesScanned: result.messagesProcessed,
    caseNotesFound: result.caseNotes.length,
    actionItemsFound: result.actionItems.length,
    caseNotesCreated: createdNotes.length,
    tasksCreated: createdTasks.length,
    notes: createdNotes,
    tasks: createdTasks,
    // Include raw action items for UI to display and allow conversion
    actionItems: result.actionItems,
    message: `Created ${createdNotes.length} case notes and ${createdTasks.length} tasks from ${result.messagesProcessed} messages`,
  });
}

// POST - Process a meeting transcript and create case notes/tasks
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { source, payload, createTasks = true, useAI = false } = body;

    if (!source || !payload) {
      return NextResponse.json(
        { error: 'source and payload are required' },
        { status: 400 }
      );
    }

    // Parse the transcript based on source
    let transcript: MeetingTranscript;

    switch (source) {
      case 'fireflies':
        transcript = parseFirefliesPayload(payload as FirefliesWebhookPayload);
        break;
      case 'fathom':
        transcript = parseFathomPayload(payload as FathomPayload);
        break;
      case 'manual':
        transcript = parseManualInput(payload as ManualTranscriptInput);
        break;
      case 'slack':
        transcript = parseSlackMessages(payload as SlackMessageInput);
        break;
      case 'email':
        transcript = parseEmailThread(payload as EmailThreadInput);
        break;
      case 'slack-channel':
        // Special handler for extracting from Slack channel with AI
        return await handleSlackChannelExtraction(payload, createTasks, useAI);
      default:
        return NextResponse.json(
          { error: `Unknown source: ${source}` },
          { status: 400 }
        );
    }

    // Parse the transcript to extract notes and action items
    // Use AI-enhanced parsing if enabled and available
    const parsedNote = useAI
      ? await parseTranscriptEnhanced(transcript, {
          useAI: true,
          clientContext: payload.clientName ? { name: payload.clientName } : undefined,
        })
      : parseTranscript(transcript);

    // Check if clientId was passed in the payload (for manual input from client context)
    let resolvedClientId = payload.clientId;

    // If clientId not provided, try to match by client name from parsing
    if (!resolvedClientId && parsedNote.clientName) {
      const clients = await getClients();
      const matchedClient = clients.find(
        c => c.name.toLowerCase().includes(parsedNote.clientName!.toLowerCase()) ||
             parsedNote.clientName!.toLowerCase().includes(c.name.toLowerCase())
      );
      if (matchedClient) {
        resolvedClientId = matchedClient.id;
      }
    }

    // Determine the case note source based on the input source
    let caseNoteSource = parsedNote.source;
    if (source === 'slack') {
      caseNoteSource = 'Slack';
    } else if (source === 'email') {
      caseNoteSource = 'Email';
    }

    // Create the case note
    const caseNote = await createCaseNote({
      title: parsedNote.title,
      clientId: resolvedClientId,
      type: parsedNote.type,
      source: caseNoteSource,
      date: parsedNote.date,
      content: parsedNote.content,
      autoGenerated: source !== 'manual',
    });

    if (!caseNote) {
      return NextResponse.json({
        success: true,
        caseNoteId: null,
        tasksCreated: 0,
        clientMatched: !!resolvedClientId,
        parsedNote: {
          title: parsedNote.title,
          type: parsedNote.type,
          actionItems: parsedNote.actionItems.map(a => a.task),
        },
        message: 'Duplicate case note detected, skipped creation',
      });
    }

    // Create tasks from action items if enabled
    const createdTasks: Array<{ id: string; task: string }> = [];
    if (createTasks && parsedNote.actionItems.length > 0 && resolvedClientId) {
      for (const actionItem of parsedNote.actionItems) {
        try {
          const task = await createTask({
            task: actionItem.task,
            clientId: resolvedClientId,
            status: 'To Do',
            urgency: actionItem.urgency,
            sourceCaseNoteId: caseNote.id,
          });
          if (task) {
            createdTasks.push({ id: task.id, task: task.task });
          }
        } catch (error) {
          console.error('Failed to create task:', actionItem.task, error);
        }
      }
    }

    return NextResponse.json({
      success: true,
      caseNoteId: caseNote.id,
      tasksCreated: createdTasks.length,
      clientMatched: !!resolvedClientId,
      parsedNote: {
        title: parsedNote.title,
        type: parsedNote.type,
        actionItems: parsedNote.actionItems.map(a => a.task),
      },
      message: `Created case note${createdTasks.length > 0 ? ` and ${createdTasks.length} tasks` : ''}`,
    });
  } catch (error) {
    console.error('Error processing transcript:', error);
    return NextResponse.json(
      { error: 'Failed to process transcript' },
      { status: 500 }
    );
  }
}
