import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { getIronSession } from 'iron-session';
import { getCaseNotes, createCaseNote, getCaseNoteStats, getCaseNotesPaginated, deleteCaseNotes } from '@/lib/notion/case-notes';
import { CaseNoteType, CaseNoteSource } from '@/types';
import { SessionData, sessionOptions } from '@/lib/auth/session';

// Natasha's email - Personal Brand team can see her meetings
const NATASHA_EMAIL = 'natasha@pivotalconversations.com.au';

// GET - List case notes with optional filters
// Supports pagination via ?paginated=true&pageSize=100&cursor=xxx
// Filtering rules:
// - Personal Brand team: See Natasha's Fireflies + their own Fireflies + ALL non-Fireflies notes (Slack, Email, Manual)
// - Other teams: See ONLY their own Fireflies notes (no non-Fireflies notes for now)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const clientId = searchParams.get('clientId') || undefined;
    const type = searchParams.get('type') as CaseNoteType | null;
    const source = searchParams.get('source') as CaseNoteSource | null;
    const limit = searchParams.get('limit');
    const stats = searchParams.get('stats') === 'true';
    const paginated = searchParams.get('paginated') === 'true';
    const pageSize = searchParams.get('pageSize');
    const cursor = searchParams.get('cursor') || undefined;

    // Get the user's session to determine what they can see
    const cookieStore = await cookies();
    const session = await getIronSession<SessionData>(cookieStore, sessionOptions);

    // Determine filtering based on team membership and admin status
    let firefliesOwnerEmails: string[] | undefined;
    let includeNonFireflies = false; // Whether to include Slack/Email/Manual notes

    if (session.isLoggedIn && session.userType === 'team') {
      const isPersonalBrand = session.team?.includes('Personal Brand');
      const isAdmin = session.isAdmin === true;

      // Admins can see all case notes (no filtering)
      if (isAdmin) {
        // Leave firefliesOwnerEmails undefined to show all notes
        includeNonFireflies = true;
      } else {
        // Build the list of Fireflies owner emails this user can see
        const allowedEmails: string[] = [];

        // Always include the user's own email for their own Fireflies meetings
        if (session.email) {
          allowedEmails.push(session.email.toLowerCase());
        }

        // Personal Brand team members can also see Natasha's Fireflies meetings
        // AND they can see all non-Fireflies notes (Slack, Email, Manual)
        if (isPersonalBrand) {
          allowedEmails.push(NATASHA_EMAIL.toLowerCase());
          includeNonFireflies = true;
        }

        // Only apply filter if we have emails to filter by
        if (allowedEmails.length > 0) {
          firefliesOwnerEmails = allowedEmails;
        }
      }
    }

    // Return stats for a specific client
    if (stats && clientId) {
      const noteStats = await getCaseNoteStats(clientId);
      const response = NextResponse.json(noteStats);
      response.headers.set('Cache-Control', 's-maxage=30, stale-while-revalidate=60');
      return response;
    }

    // Return paginated response if requested
    if (paginated) {
      const result = await getCaseNotesPaginated({
        clientId,
        type: type || undefined,
        source: source || undefined,
        pageSize: pageSize ? parseInt(pageSize) : 100,
        cursor,
        firefliesOwnerEmails,
        includeNonFireflies,
      });
      const response = NextResponse.json(result);
      response.headers.set('Cache-Control', 's-maxage=30, stale-while-revalidate=60');
      return response;
    }

    const notes = await getCaseNotes({
      clientId,
      type: type || undefined,
      source: source || undefined,
      limit: limit ? parseInt(limit) : undefined,
      firefliesOwnerEmails,
      includeNonFireflies,
    });

    const response = NextResponse.json(notes);
    response.headers.set('Cache-Control', 's-maxage=30, stale-while-revalidate=60');
    return response;
  } catch (error) {
    console.error('Error fetching case notes:', error);
    return NextResponse.json(
      { error: 'Failed to fetch case notes' },
      { status: 500 }
    );
  }
}

// POST - Create new case note
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { title, clientId, date, type, source, fullNote, autoGenerated } = body;

    if (!title || !clientId || !type || !source || !fullNote) {
      return NextResponse.json(
        { error: 'Title, clientId, type, source, and fullNote are required' },
        { status: 400 }
      );
    }

    const note = await createCaseNote({
      title,
      clientId,
      date,
      type,
      source,
      fullNote,
      autoGenerated,
    });

    return NextResponse.json(note, { status: 201 });
  } catch (error) {
    console.error('Error creating case note:', error);
    return NextResponse.json(
      { error: 'Failed to create case note' },
      { status: 500 }
    );
  }
}

// DELETE - Bulk delete case notes
export async function DELETE(request: NextRequest) {
  try {
    const body = await request.json();
    const { ids } = body;

    if (!ids || !Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json(
        { error: 'Array of case note IDs is required' },
        { status: 400 }
      );
    }

    const result = await deleteCaseNotes(ids);

    return NextResponse.json({
      success: true,
      deleted: result.deleted,
      failed: result.failed,
    });
  } catch (error) {
    console.error('Error deleting case notes:', error);
    return NextResponse.json(
      { error: 'Failed to delete case notes' },
      { status: 500 }
    );
  }
}
